route:
  group_by: ['alertname', 'symbol']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'default-receiver'

receivers:
  - name: 'default-receiver'
    email_configs:
      - to: 'danielfisher0@gmail.com'
        from: 'danielfisher0@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'danielfisher0@gmail.com'
        auth_password: 'dummy'
        require_tls: true
