"""Fade-exploitation seeds: signed fade conviction (fair - mid), gated by mean-reversion regime.

Positive => mid below fair => long toward fair. np.nan => abstain. Level-free (returns +
microstructure). Gates: variance-ratio (Lo-MacKinlay 1988), lag-1 autocorrelation, Kaufman
efficiency ratio, extreme-dislocation; OU half-life (Leung-Li, Bertram) as an idea.
"""

_FAIR = (
    "    r = ctx.col('vel_pips_h1'); n = r.shape[0]; a = 0.05\n"
    "    p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
    "    ew = np.empty(n); acc = p[0]\n"
    "    for i in range(n):\n"
    "        acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
    "    dev = ew - p  # fair - mid (pips); >0 => mid below fair => fade long\n"
)


def _cond_response_src(H: int) -> str:
    return (
        "def signal(ctx):\n" + _FAIR +
        f"    H = {H}; W = 240; MINEP = 20\n"
        "    ad = np.abs(np.where(np.isfinite(dev), dev, 0.0))\n"
        "    c1 = np.concatenate(([0.0], np.cumsum(ad)))\n"
        "    c2 = np.concatenate(([0.0], np.cumsum(ad * ad)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); mwin = (k - lo).astype(float)\n"
        "    ms = np.where(mwin > 0, mwin, 1.0)\n"
        "    mu = (c1[k] - c1[lo]) / ms; var = (c2[k] - c2[lo]) / ms - mu * mu\n"
        "    sd = np.sqrt(np.clip(var, 1e-12, None))\n"
        "    ext = (mwin >= 60) & (ad > mu + 2.0 * sd)\n"
        "    pf = np.full(n, np.nan); pf[:n - H] = p[H:] - p[:n - H]\n"
        "    fr = np.sign(dev) * pf\n"
        "    valid = ext & np.isfinite(fr)\n"
        "    resolved = np.full(n, np.nan)\n"
        "    j = np.nonzero(valid)[0]; resolved[j + H] = fr[j]\n"
        "    fin = np.isfinite(resolved)\n"
        "    rv = np.where(fin, resolved, 0.0); cnt = np.where(fin, 1.0, 0.0)\n"
        "    nep = np.cumsum(cnt)\n"
        "    R = np.cumsum(rv) / np.maximum(nep, 1.0)\n"
        "    direction = np.where(R >= 0.0, 1.0, -1.0)\n"
        "    out = np.where(nep >= MINEP, dev * direction, np.nan)\n"
        "    return out\n"
    )


# ── Branch taxonomy ──────────────────────────────────────────────────────────
# Each branch is a distinct literature-backed strategy family.  The diversity bonus
# in PUCT selection explicitly rewards under-explored branches so the search does not
# collapse into parameter-tweaking the single best-scoring seed.
BRANCH_TAXONOMY: dict[str, str] = {
    "baseline": "Raw fair-mid deviation with no gate or direction model.",
    "mean_reversion_gate": "Fade toward fair, gated by a microstructure mean-reversion detector.",
    "regime_switching": "Direction chosen by regime (fade in mean-reverting windows, continue in trending).",
    "empirical_direction": "Direction learned online from past completed episodes; no assumed reversion.",
    "adaptive_estimation": "Fair-price estimator adapts to local volatility (Parkinson EWMA).",
    "microstructure_gate": "Gate using order-flow imbalance proxy (range-return correlation).",
    "liquidity_gate": "Gate using liquidity-quality metrics (spread, volatility) to block trades during degraded market conditions.",
    "transient_impact": "Adjust fair price for decaying trade impact (propagator model) before computing deviation.",
    "jump_aware": "Detect jump bars from range outliers and abstain during + post-jump cooling-off periods.",
    "flow_intensity": "Gate fades during self-exciting directional flow episodes (Hawkes-style magnitude persistence).",
    "asymmetric_vol": "Gate fades when downside Parkinson volatility dominates upside (bad-volatility regime).",
    "seasonality": "Gate fades during FX fix windows where microstructure is distorted by fix-order flow.",
    "microprice": "Imbalance-weighted fair value (Stoikov microprice proxy): shift fair toward the side the bar closed on; fade deviation from microprice rather than from a symmetric EWMA.",
    "flow_toxicity": "Gate fades by order-flow toxicity (VPIN proxy): abstain when the EWMA of |signed flow| / total flow is high (informed/directional flow); fade only into balanced, uninformed flow.",
}

# ── Seed-to-branch mapping ───────────────────────────────────────────────────
SEED_BRANCH_TAGS: dict[str, str] = {
    "fair_fade": "baseline",
    "vr_gated_fade": "mean_reversion_gate",
    "vr_conditional_direction": "regime_switching",
    "autocorr_gated_fade": "mean_reversion_gate",
    "efficiency_gated_fade": "mean_reversion_gate",
    "extreme_fade": "mean_reversion_gate",
    "conditional_response_fade": "empirical_direction",
    "conditional_response_fade_h200": "empirical_direction",
    "conditional_response_fade_h400": "empirical_direction",
    "conditional_response_signed": "empirical_direction",
    "adaptive_fair": "adaptive_estimation",
    "ofi_gated_fade": "microstructure_gate",
    "spread_vol_gate": "liquidity_gate",
    "transient_impact_fade": "transient_impact",
    "jump_aware_fade": "jump_aware",
    "hawkes_gate": "flow_intensity",
    "asymmetric_vol_gate": "asymmetric_vol",
    "fix_window_gate": "seasonality",
    "microprice_fade": "microprice",
    "vpin_gated_fade": "flow_toxicity",
}

# ── Rich prompt templates (one per branch) ───────────────────────────────────
# These replace the one-sentence RESEARCH_IDEAS with full context: formula,
# rationale, reference implementation, allowed parameter bounds, and known
# failure patterns.  The LLM now has enough signal to write correct causal
# code rather than guessing from a 10-line abstract.
RICH_TEMPLATES: dict[str, str] = {
    "baseline": (
        "BRANCH: baseline — raw fair-mid deviation\n"
        "FORMULA: dev = EWMA(cumsum(returns), alpha=0.05) - cumsum(returns)\n"
        "RATIONALE: The EWMA smooths the cumulative price to estimate a short-term fair value."
        " When mid is below fair (dev > 0), the instrument is cheap; the signal is pure fade.\n"
        "NO GATE: Every bar gets a position. This is the simplest benchmark.\n"
        "ALLOWED VARIATIONS: alpha ∈ {0.03, 0.05, 0.10}\n"
        "REFERENCE IMPLEMENTATION:\n"
        "```python\n"
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); n = r.shape[0]; a = 0.05\n"
        "    p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n):\n"
        "        acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    return dev\n"
        "```\n"
        "FAILURE PATTERN: Varying alpha too high (>0.15) makes the EWMA lag so far that the"
        " deviation signal is stale and the edge collapses.\n"
    ),
    "mean_reversion_gate": (
        "BRANCH: mean_reversion_gate — fade only when microstructure says revert\n"
        "FORMULA (Lo-MacKinlay variance ratio):\n"
        "    VR(q) = Var(sum_{i=0}^{q-1} r_{t+i}) / (q * Var(r_t))\n"
        "    Gate opens when VR < threshold (mean-reverting) and window is mature (m >= 60).\n"
        "RATIONALE: Lo & MacKinlay (1988, Review of Financial Studies).  When q-step variance"
        " is below q times the 1-step variance, price changes partially reverse; the process is"
        " mean-reverting.  The gate prevents fading during strong trends where reversion does not pay.\n"
        "WHY W=240: At 100-tick bars this is ~1 trading day (EURUSD), giving enough samples for"
        " a stable variance estimate without reacting to intraday noise.\n"
        "WHY qv=20: This horizon matches the observed mean-reversion half-life on EURUSD (~20 bars).\n"
        "CUMSUM TRICK: rollvar uses np.cumsum instead of np.convolve to avoid O(n·W) memory"
        " allocation on large arrays.  The stability constant 1e-12 prevents division by zero"
        " when v1=0 during flat sessions.\n"
        "ALLOWED VARIATIONS:\n"
        "    W ∈ {60, 120, 240}     (window length in bars)\n"
        "    qv ∈ {10, 20, 40}      (variance-ratio horizon)\n"
        "    threshold ∈ {0.95, 1.0, 1.05}\n"
        "REFERENCE IMPLEMENTATION:\n"
        "```python\n"
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); n = r.shape[0]; a = 0.05\n"
        "    p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n):\n"
        "        acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    W = 240; qv = 20\n"
        "    d1 = np.diff(p, prepend=p[0])\n"
        "    dq = np.empty(n); dq[:qv] = 0.0; dq[qv:] = p[qv:] - p[:-qv]\n"
        "    def rollvar(x):\n"
        "        c1 = np.concatenate(([0.0], np.cumsum(x)))\n"
        "        c2 = np.concatenate(([0.0], np.cumsum(x * x)))\n"
        "        k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "        ms = np.where(m > 0, m, 1.0)\n"
        "        mu = (c1[k] - c1[lo]) / ms\n"
        "        return (c2[k] - c2[lo]) / ms - mu * mu, m\n"
        "    v1, m = rollvar(d1); vq, _ = rollvar(dq)\n"
        "    vr = vq / (qv * v1 + 1e-12)\n"
        "    out = np.where((m >= 60) & (vr < 1.0), dev, np.nan)\n"
        "    return out\n"
        "```\n"
        "FAILURE PATTERNS:\n"
        "  - W=60 is too short: variance estimate is noisy, gate flips randomly, edge dies.\n"
        "  - threshold=1.05 is too loose: gate barely filters, behaves like baseline.\n"
        "  - Forgetting m >= 60: trades before window is mature, uses garbage variance.\n"
        "  - Omitting 1e-12: division by zero on flat sessions crashes or gives inf.\n"
        "CROSS-BRIDGE: Can combine with extreme_fade gate (AND) to only fade at tails.\n"
    ),
    "regime_switching": (
        "BRANCH: regime_switching — direction chosen by microstructure regime, not assumed\n"
        "FORMULA (Lo-MacKinlay with dual threshold):\n"
        "    VR(q) = Var(sum_{i=0}^{q-1} r_{t+i}) / (q * Var(r_t))\n"
        "    if VR < 0.95:  mean-reverting  -> FADE  (return +dev)\n"
        "    if VR > 1.05:  trending       -> CONTINUE (return -dev)\n"
        "    else:           dead-band     -> abstain (return nan)\n"
        "RATIONALE: Same variance-ratio detector as mean_reversion_gate, but the literature also"
        " tells us VR > 1 identifies trending regimes where fading is harmful.  Instead of"
        " assuming fade, the rule picks the side empirically per regime.  This is the only"
        " seed family that explicitly exploits continuation on EURUSD when it is trending.\n"
        "WHY 0.95 / 1.05 DEAD BAND: Avoids noisy regime flips near VR=1.  The thresholds create"
        " a confidence interval; we only trade when the regime is clear.\n"
        "ALLOWED VARIATIONS:\n"
        "    W ∈ {60, 120, 240}\n"
        "    qv ∈ {10, 20, 40}\n"
        "    lower_threshold ∈ {0.90, 0.95, 0.98}\n"
        "    upper_threshold ∈ {1.02, 1.05, 1.10}\n"
        "REFERENCE IMPLEMENTATION:\n"
        "```python\n"
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); n = r.shape[0]; a = 0.05\n"
        "    p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n):\n"
        "        acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    W = 240; qv = 20\n"
        "    d1 = np.diff(p, prepend=p[0])\n"
        "    dq = np.empty(n); dq[:qv] = 0.0; dq[qv:] = p[qv:] - p[:-qv]\n"
        "    def rollvar(x):\n"
        "        c1 = np.concatenate(([0.0], np.cumsum(x)))\n"
        "        c2 = np.concatenate(([0.0], np.cumsum(x * x)))\n"
        "        k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "        ms = np.where(m > 0, m, 1.0)\n"
        "        mu = (c1[k] - c1[lo]) / ms\n"
        "        return (c2[k] - c2[lo]) / ms - mu * mu, m\n"
        "    v1, m = rollvar(d1); vq, _ = rollvar(dq)\n"
        "    vr = vq / (qv * v1 + 1e-12)\n"
        "    out = np.full(n, np.nan); ok = m >= 60\n"
        "    out = np.where(ok & (vr < 0.95),  dev, out)\n"
        "    out = np.where(ok & (vr > 1.05), -dev, out)\n"
        "    return out\n"
        "```\n"
        "FAILURE PATTERNS:\n"
        "  - Tight dead-band (0.98 / 1.02): too many false regime flips, edge collapses.\n"
        "  - Wide dead-band (0.90 / 1.10): too few trades, capacity drops below viable level.\n"
        "  - Using same threshold for both (e.g. <1.0 vs >1.0): noisy, behaves like random.\n"
        "CROSS-BRIDGE: Can combine with empirical_direction (conditional_response) — use VR"
        " regime to pick H horizon, or use conditional-response direction instead of the fixed"
        " fade/continue rule.\n"
    ),
    "empirical_direction": (
        "BRANCH: empirical_direction — learn direction from past completed episodes, no assumption\n"
        "FORMULA:\n"
        "    1. Identify extreme dislocation bars: |dev| > mu(|dev|) + 2*sigma(|dev|) over trailing W.\n"
        "    2. Look forward H bars to see how each dislocation resolved: pf = p[t+H] - p[t].\n"
        "    3. Compute cumulative mean of resolved returns: R = cumsum(resolved) / cumsum(count).\n"
        "    4. Direction = sign(R): if past extremes reverted on average, fade; if they continued,\n"
        "       go with the move.\n"
        "    5. Only trade when nep >= MINEP (enough completed episodes for a stable direction estimate).\n"
        "RATIONALE (Bertram 2010; Leung & Li 2015):  OU process estimators give theoretical half-life,"
        " but empirical reality is noisy.  This online learner treats each completed extreme episode"
        " as a training example and updates a causal mean.  It learns per-symbol, per-regime, with"
        " no peeking — resolved[t] is only known at t+H.\n"
        "WHY H=100/200/400: These match the candidate-state exit horizons.  A fixed-H learner with"
        " H mismatched to the exit horizon misclassifies outcomes.\n"
        "WHY MINEP=20: Enough episodes for a direction sign to be stable, but not so high that"
        " the learner waits forever in low-volatility regimes.\n"
        "SIGNED VARIANT: Separate direction learners for positive-deviation episodes vs negative-"
        "deviation episodes, because EUR and JPY may have asymmetric reversion dynamics.\n"
        "ALLOWED VARIATIONS:\n"
        "    W ∈ {120, 240}         (extreme-detection window)\n"
        "    H ∈ {100, 200, 400}    (forward-learning horizon, MUST match exit horizon)\n"
        "    MINEP ∈ {10, 20, 30}   (minimum episodes before trusting direction)\n"
        "    signed ∈ {True, False}  (separate learners for positive vs negative deviations)\n"
        "REFERENCE IMPLEMENTATION (H=200, unsigned):\n"
        "```python\n"
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); n = r.shape[0]; a = 0.05\n"
        "    p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n):\n"
        "        acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    H = 200; W = 240; MINEP = 20\n"
        "    ad = np.abs(np.where(np.isfinite(dev), dev, 0.0))\n"
        "    c1 = np.concatenate(([0.0], np.cumsum(ad)))\n"
        "    c2 = np.concatenate(([0.0], np.cumsum(ad * ad)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); mwin = (k - lo).astype(float)\n"
        "    ms = np.where(mwin > 0, mwin, 1.0)\n"
        "    mu = (c1[k] - c1[lo]) / ms; var = (c2[k] - c2[lo]) / ms - mu * mu\n"
        "    sd = np.sqrt(np.clip(var, 1e-12, None))\n"
        "    ext = (mwin >= 60) & (ad > mu + 2.0 * sd)\n"
        "    pf = np.full(n, np.nan); pf[:n - H] = p[H:] - p[:n - H]\n"
        "    fr = np.sign(dev) * pf\n"
        "    valid = ext & np.isfinite(fr)\n"
        "    resolved = np.full(n, np.nan)\n"
        "    j = np.nonzero(valid)[0]; resolved[j + H] = fr[j]\n"
        "    fin = np.isfinite(resolved)\n"
        "    rv = np.where(fin, resolved, 0.0); cnt = np.where(fin, 1.0, 0.0)\n"
        "    nep = np.cumsum(cnt)\n"
        "    R = np.cumsum(rv) / np.maximum(nep, 1.0)\n"
        "    direction = np.where(R >= 0.0, 1.0, -1.0)\n"
        "    out = np.where(nep >= MINEP, dev * direction, np.nan)\n"
        "    return out\n"
        "```\n"
        "FAILURE PATTERNS:\n"
        "  - H=400 on a low-vol symbol: too few completed episodes within a month, direction"
        "    never stabilises (nep < MINEP for most bars).\n"
        "  - H=100 on a trending symbol: direction flips too fast, chases noise.\n"
        "  - MINEP=5: direction estimate is noisy, false flips kill edge.\n"
        "  - MINEP=50: too conservative, trades vanish, capacity drops to zero.\n"
        "CROSS-BRIDGE: Can combine with regime_switching — use VR to pick H dynamically per bar,"
        " or use the empirical direction as the direction rule inside a variance-ratio gate.\n"
    ),
    "adaptive_estimation": (
        "BRANCH: adaptive_estimation — fair price adapts to local volatility via Parkinson EWMA\n"
        "FORMULA:\n"
        "    1. Parkinson vol = sqrt( sum(range^2) / (4*ln2 * W) )  (causal trailing window)\n"
        "    2. alpha = clip( 0.02 + 0.08 * (vol / vol_median), 0.02, 0.10 )\n"
        "    3. fair_i = (1-alpha_i)*fair_{i-1} + alpha_i*mid_i   (per-bar adaptive alpha)\n"
        "RATIONALE (Taylor 2017, J. Financial Econometrics):\n"
        "  A fixed EWMA alpha assumes constant volatility.  In FX, volatility clusters:\n"
        "  post-news spikes, Asian-session calm, London open surges.  The Parkinson estimator\n"
        "  uses bar_range (high-low) which is more efficient than close-close variance.\n"
        "  Higher vol -> faster alpha catches dislocations quicker; lower vol -> smoother fair\n"
        "  avoids noise-driven false deviations.\n"
        "BAYESIAN ALIGNMENT:\n"
        "  The adaptive fair may change trade frequency (fewer trades in calm periods).  The\n"
        "  monthly_net aggregation still works, but watch for months with < 20 trades where\n"
        "  the StudentT SE inflates.  If a month drops below _MIN_MONTHS threshold, the\n"
        "  Bayesian posterior loses that observation.\n"
        "ALLOWED VARIATIONS:\n"
        "    W ∈ {10, 20, 40}       (Parkinson window)\n"
        "    alpha_min ∈ {0.01, 0.02} (floor to prevent over-smoothing)\n"
        "    alpha_max ∈ {0.08, 0.10, 0.15} (cap to prevent noise chasing)\n"
        "REFERENCE IMPLEMENTATION:\n"
        "```python\n"
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); br = ctx.col('bar_range_pips')\n"
        "    n = r.shape[0]; W = 20\n"
        "    c = np.concatenate(([0.0], np.cumsum(br * br)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "    ms = np.where(m > 0, m, 1.0)\n"
        "    parkinson = np.sqrt(np.clip((c[k]-c[lo])/(ms*4.0*np.log(2.0)), 1e-12, None))\n"
        "    vol_cum = np.cumsum(np.where(np.isfinite(parkinson), parkinson, 0.0))\n"
        "    vol_cnt = np.cumsum(np.where(np.isfinite(parkinson), 1.0, 0.0))\n"
        "    vol_ref = vol_cum / np.maximum(vol_cnt, 1.0)\n"
        "    alpha = np.clip(0.02 + 0.08*(parkinson/(vol_ref+1e-9)), 0.02, 0.10)\n"
        "    p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n):\n"
        "        acc = (1-alpha[i])*acc + alpha[i]*p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    return dev\n"
        "```\n"
        "FAILURE PATTERNS:\n"
        "  - W=10: Parkinson estimate is noisy, alpha oscillates, fair price chatters.\n"
        "  - alpha_max=0.15: fair catches noise, false deviations proliferate.\n"
        "  - alpha_min=0.01: too sluggish after vol spikes, fair is stale.\n"
        "CROSS-BRIDGE: Can combine with ANY gate — the adaptive fair replaces the fixed-alpha\n"
        "  EWMA in the baseline; gates (VR, autocorr, OFI) still apply to the same dev signal.\n"
    ),
    "microstructure_gate": (
        "BRANCH: microstructure_gate — gate fades using order-flow imbalance proxy\n"
        "FORMULA (Cont-Kukanov 2017, J. Financial Econometrics):\n"
        "    1. rrc = Pearson(|return|, bar_range) over trailing W bars\n"
        "    2. Gate: fade only when |rrc| < threshold (uncorrelated => noise, good fade)\n"
        "RATIONALE:\n"
        "  Without Level-2 order book data, we approximate OFI by correlating bar range with\n"
        "  bar return.  When large range co-occurs with large directional move → informed flow\n"
        "  (trending, do NOT fade).  When large range has small return → noise / choppy\n"
        "  (mean-reverting, DO fade).  This is a microstructure-informed gate that needs no\n"
        "  external data — only bar_range_pips and returns, both in the existing feature set.\n"
        "BAYESIAN ALIGNMENT:\n"
        "  The gate should NOT be too tight (threshold < 0.1) or monthly trade counts drop\n"
        "  below viable levels.  The Bayesian model needs at least _MIN_MONTHS=2 active months\n"
        "  per symbol; a dead gate produces zero trades and fails the posterior entirely.\n"
        "ALLOWED VARIATIONS:\n"
        "    W ∈ {10, 20, 40}         (correlation window)\n"
        "    threshold ∈ {0.2, 0.3, 0.5} (|rrc| below which we fade; higher => more trades)\n"
        "REFERENCE IMPLEMENTATION:\n"
        "```python\n"
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); br = ctx.col('bar_range_pips')\n"
        "    n = r.shape[0]; W = 20\n"
        "    absr = np.abs(np.where(np.isfinite(r), r, 0.0))\n"
        "    s_x = np.concatenate(([0.0], np.cumsum(absr)))\n"
        "    s_y = np.concatenate(([0.0], np.cumsum(br)))\n"
        "    s_xy = np.concatenate(([0.0], np.cumsum(absr*br)))\n"
        "    s_x2 = np.concatenate(([0.0], np.cumsum(absr*absr)))\n"
        "    s_y2 = np.concatenate(([0.0], np.cumsum(br*br)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "    ms = np.where(m > 0, m, 1.0)\n"
        "    mx = (s_x[k]-s_x[lo])/ms; my = (s_y[k]-s_y[lo])/ms\n"
        "    mxy = (s_xy[k]-s_xy[lo])/ms\n"
        "    mx2 = (s_x2[k]-s_x2[lo])/ms; my2 = (s_y2[k]-s_y2[lo])/ms\n"
        "    cov = mxy - mx*my\n"
        "    var_x = np.clip(mx2 - mx*mx, 1e-12, None)\n"
        "    var_y = np.clip(my2 - my*my, 1e-12, None)\n"
        "    rrc = cov / np.sqrt(var_x * var_y)\n"
        "    # Baseline fair estimator\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1-a)*acc + a*p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    out = np.where((m >= 10) & (np.abs(rrc) < 0.3), dev, np.nan)\n"
        "    return out\n"
        "```\n"
        "FAILURE PATTERNS:\n"
        "  - W=10: correlation is unstable, gate flips randomly.\n"
        "  - threshold=0.1: too tight, <5% of bars pass, monthly counts collapse.\n"
        "  - threshold=0.5: too loose, gate does nothing, behaves like baseline.\n"
        "CROSS-BRIDGE: Can combine with mean_reversion_gate (VR) or empirical_direction —\n"
        "  use OFI as a pre-filter, then apply VR or conditional-response inside the filtered bars.\n"
    ),
    "liquidity_gate": (
        "BRANCH: liquidity_gate — gate fades using liquidity-quality metrics\n"
        "FORMULA (Ranaldo & Santucci de Magistris 2022, J. Econometrics):\n"
        "    1. Parkinson vol = sqrt( sum(range^2) / (4*ln2*W) )  (causal trailing window)\n"
        "    2. pv_ref = expanding_mean(Parkinson vol)  (causal reference)\n"
        "    3. Gate: fade only when |spread_z| <= threshold AND Parkinson vol <= 1.5 * pv_ref\n"
        "RATIONALE:\n"
        "  When spread is wide (spread_z > 2.0) or volatility is unusually elevated\n"
        "  (Parkinson > 1.5 * its own expanding mean), the fair-price model degrades.\n"
        "  These are transient illiquidity or news events where microstructure noise dominates.\n"
        "  Blocking trades during these periods removes disproportionately loss-making entries.\n"
        "  This is especially relevant for JPY/CHF which have wider spreads and erratic vol.\n"
        "BAYESIAN ALIGNMENT:\n"
        "  This gate blocks ~10-20% of bars. For a typical month (~1500 bars/pair),\n"
        "  that leaves 1200-1350 trades — still ample for StudentT hierarchical inference.\n"
        "  A threshold < 1.5 sigma risks collapsing monthly counts below _MIN_MONTHS=2.\n"
        "ALLOWED VARIATIONS:\n"
        "    W ∈ {10, 20, 40}         (Parkinson window)\n"
        "    spread_threshold ∈ {1.5, 2.0, 2.5}  (spread_z above which we block)\n"
        "    vol_multiplier ∈ {1.2, 1.5, 2.0}   (Parkinson vol multiplier for reference)\n"
        "REFERENCE IMPLEMENTATION:\n"
        "```python\n"
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); br = ctx.col('bar_range_pips'); sz = ctx.col('spread_z')\n"
        "    n = r.shape[0]; W = 20\n"
        "    # Parkinson volatility (causal trailing)\n"
        "    c = np.concatenate(([0.0], np.cumsum(br * br)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "    ms = np.where(m > 0, m, 1.0)\n"
        "    parkinson = np.sqrt(np.clip((c[k]-c[lo])/(ms*4.0*np.log(2.0)), 1e-12, None))\n"
        "    # Causal expanding mean of Parkinson vol\n"
        "    pv_cum = np.cumsum(np.where(np.isfinite(parkinson), parkinson, 0.0))\n"
        "    pv_cnt = np.cumsum(np.where(np.isfinite(parkinson), 1.0, 0.0))\n"
        "    pv_ref = pv_cum / np.maximum(pv_cnt, 1.0)\n"
        "    # Gate: normal spread AND normal volatility\n"
        "    gate_ok = (np.abs(sz) <= 2.0) & (parkinson <= 1.5 * pv_ref)\n"
        "    # Baseline fair estimator\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1-a)*acc + a*p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    out = np.where((m >= 10) & gate_ok, dev, np.nan)\n"
        "    return out\n"
        "```\n"
        "FAILURE PATTERNS:\n"
        "  - spread_threshold=1.0: blocks ~40% of bars, monthly counts may drop below viable.\n"
        "  - spread_threshold=3.0: too lenient, gate rarely fires, no edge improvement.\n"
        "  - vol_multiplier=1.0: blocks almost nothing in normal markets.\n"
        "  - vol_multiplier=3.0: blocks too much, misses genuine fade opportunities.\n"
        "CROSS-BRIDGE: Can combine with ANY gate — use liquidity as a first-pass filter,\n"
        "  then apply VR, autocorr, or OFI on the remaining bars.\n"
    ),
    "transient_impact": (
        "BRANCH: transient_impact — adjust fair price for decaying trade impact before fading\n"
        "FORMULA (Barzykin 2025/2026, arXiv:2601.13421):\n"
        "    1. impact_t = (1 - rho) * impact_{t-1} + lambda * range_{t-1}   (causal decay)\n"
        "    2. dev_adj = dev - impact_t                                 (impact-cleansed deviation)\n"
        "    3. Gate: |impact_t| <= 2.0 * expanding_mean(|impact|)      (don't trade when impact is extreme)\n"
        "RATIONALE:\n"
        "  In FX, trades cause transient impact that decays exponentially (Obizhaeva-Wang style).\n"
        "  The observed mid is distorted upward by past buying impact and downward by past selling.\n"
        "  Fading the raw fair-mid deviation means fading a stale, impact-distorted fair price.\n"
        "  By subtracting the estimated decaying impact, we get a cleansed deviation that reflects\n"
        "  true fair-mid mispricing rather than mechanical price pressure.\n"
        "  This is especially important for JPY/CHF which have wider spreads and more erratic flow.\n"
        "BAYESIAN ALIGNMENT:\n"
        "  The adjustment is continuous, not a hard gate, so monthly trade counts stay similar\n"
        "  to baseline.  The gate (|impact| < 2x mean) blocks only when impact is extreme —\n"
        "  typically <10% of bars.  This preserves the monthly sample size needed for StudentT.\n"
        "ALLOWED VARIATIONS:\n"
        "    rho ∈ {0.05, 0.10, 0.20}      (decay per bar; higher = faster forget)\n"
        "    lambda ∈ {0.3, 0.5, 0.8}      (impact coefficient; pips distortion per pips of range)\n"
        "    gate_multiplier ∈ {1.5, 2.0, 3.0} (multiple of mean |impact| for gate)\n"
        "REFERENCE IMPLEMENTATION:\n"
        "```python\n"
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); br = ctx.col('bar_range_pips')\n"
        "    n = r.shape[0]\n"
        "    # Baseline fair estimator\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    # Transient impact: decaying sum of past bar ranges (Barzykin 2025/2026)\n"
        "    rho = 0.1; lam = 0.5\n"
        "    impact = np.zeros(n)\n"
        "    for i in range(1, n): impact[i] = (1 - rho) * impact[i-1] + lam * br[i-1]\n"
        "    dev_adj = dev - impact\n"
        "    # Gate: only trade when impact is not extreme (causal expanding mean)\n"
        "    iabs = np.abs(impact); ic = np.cumsum(iabs)\n"
        "    imean = ic / np.maximum(np.arange(1, n + 1), 1.0)\n"
        "    gate_ok = iabs <= 2.0 * imean\n"
        "    out = np.where(gate_ok, dev_adj, np.nan)\n"
        "    return out\n"
        "```\n"
        "FAILURE PATTERNS:\n"
        "  - rho=0.50: impact decays too fast, barely different from raw deviation.\n"
        "  - rho=0.01: impact accumulates endlessly, dev_adj drifts to zero.\n"
        "  - lambda=2.0: over-corrects, dev_adj flips sign and chases noise.\n"
        "  - gate_multiplier=1.0: blocks almost nothing, no protection from extreme impact.\n"
        "  - gate_multiplier=5.0: blocks too much, monthly counts may drop below viable.\n"
        "CROSS-BRIDGE: Can combine with adaptive_estimation — adaptive alpha for fair +\n"
        "  impact adjustment for distortion = a fair price that responds to both vol and flow.\n"
    ),
    "jump_aware": (
        "BRANCH: jump_aware — detect jump bars and abstain during + post-jump cooling-off\n"
        "FORMULA (Bibinger, Hautsch & Ristig 2024, arXiv:2403.00819):\n"
        "    1. Parkinson vol = sqrt( sum(range^2) / (4*ln2*W) )  (causal trailing window)\n"
        "    2. jump_t = range_t > k_jump * parkinson_t            (bar is an outlier)\n"
        "    3. Gate: abstain if ANY jump in [t-cooldown+1, t]    (causal cooling-off)\n"
        "RATIONALE:\n"
        "  Aït-Sahalia, Li & Li (NBER 2024) show >85% of intraday jumps have no identifiable news.\n"
        "  These are microstructure artifacts — large orders, algo cascades, or quote stuffing.\n"
        "  During a jump, the efficient price itself is discontinuous; the fair-price model breaks\n"
        "  because fair is a smooth EWMA that cannot track a discontinuous move.  Fading during\n"
        "  or immediately after a jump means fading a stale fair into a new price regime.\n"
        "  Bibinger et al. (2024) show that local-extrema (High/Low) methods detect these jumps\n"
        "  faster than return-based pre-averaging.  We proxy this with bar_range outliers.\n"
        "BAYESIAN ALIGNMENT:\n"
        "  Typically blocks ~5-15% of bars (jumps are rare).  cooldown controls the post-jump\n"
        "  abstention: 3 bars ≈ minimal protection; 8 bars ≈ conservative but may drop counts\n"
        "  on jumpy symbols (JPY).  Keep cooldown <= 8 to preserve monthly viability.\n"
        "ALLOWED VARIATIONS:\n"
        "    W ∈ {10, 20, 40}         (Parkinson window)\n"
        "    k_jump ∈ {3.0, 4.0, 5.0}  (range multiple for jump detection)\n"
        "    cooldown ∈ {3, 5, 8}      (bars to abstain after a jump)\n"
        "REFERENCE IMPLEMENTATION:\n"
        "```python\n"
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); br = ctx.col('bar_range_pips')\n"
        "    n = r.shape[0]; W = 20\n"
        "    # Parkinson volatility (causal trailing)\n"
        "    c = np.concatenate(([0.0], np.cumsum(br * br)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "    ms = np.where(m > 0, m, 1.0)\n"
        "    parkinson = np.sqrt(np.clip((c[k]-c[lo])/(ms*4.0*np.log(2.0)), 1e-12, None))\n"
        "    # Jump detection: bar range > k * Parkinson vol\n"
        "    jump = br > 4.0 * parkinson\n"
        "    # Causal cooling-off: abstain for cooldown bars after any jump\n"
        "    cooldown = 5\n"
        "    cj = np.concatenate(([0.0], np.cumsum(jump.astype(float))))\n"
        "    lo_cd = np.maximum(0, k - cooldown + 1)\n"
        "    recent_jump = (cj[k + 1] - cj[lo_cd]) > 0\n"
        "    gate_ok = ~recent_jump\n"
        "    # Baseline fair estimator\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    out = np.where((m >= 10) & gate_ok, dev, np.nan)\n"
        "    return out\n"
        "```\n"
        "FAILURE PATTERNS:\n"
        "  - k_jump=2.0: too sensitive, blocks ~30% of bars, monthly counts collapse.\n"
        "  - k_jump=6.0: too conservative, misses actual jumps, no edge improvement.\n"
        "  - cooldown=15: blocks too long after rare jumps, loses recovery trades.\n"
        "  - cooldown=1: insufficient protection, still fades into jump aftermath.\n"
        "CROSS-BRIDGE: Can combine with ANY gate — use jump detection as a temporal\n"
        "  first-pass filter, then apply VR, OFI, or liquidity on the remaining bars.\n"
    ),
    "flow_intensity": (
        "BRANCH: flow_intensity — gate fades during self-exciting directional flow episodes\n"
        "FORMULA (Nittur & Jain 2025, Computational Economics; Rambaldi et al. 2015, Phys Rev E):\n"
        "    1. intensity_t = beta * intensity_{t-1} + alpha * |return_t|   (causal EWMA of magnitude)\n"
        "    2. ref_t = expanding_mean(intensity)                         (causal reference)\n"
        "    3. Gate: fade only when intensity_t <= k * ref_t            (abstain when self-exciting)\n"
        "RATIONALE:\n"
        "  Order flow in FX is self-exciting: a large directional bar increases the probability\n"
        "  of another large directional bar in the near future (Hawkes process).  During these\n"
        "  self-exciting episodes, directional pressure persists and fading is dangerous — the\n"
        "  market keeps moving in the same direction.  The intensity is a causal EWMA of return\n"
        "  magnitude; when it spikes above its own expanding mean, the flow is self-exciting.\n"
        "  This is distinct from the OFI gate (range-return correlation) which asks whether\n"
        "  THIS bar is informed or noise.  Hawkes intensity asks whether the RECENT FLOW is\n"
        "  self-exciting.  A bar can have low range-return correlation (noise-like) but still sit\n"
        "  in a self-exciting cascade.\n"
        "BAYESIAN ALIGNMENT:\n"
        "  Typically blocks ~10-20% of bars during high-activity episodes.  Monthly counts\n"
        "  remain viable because intensity is continuous and only extremes are gated.\n"
        "  Keep k >= 1.5 to avoid over-blocking; k <= 3.0 to retain protection.\n"
        "ALLOWED VARIATIONS:\n"
        "    alpha ∈ {0.2, 0.3, 0.5}      (new-event weight; higher = more reactive)\n"
        "    beta ∈ {0.5, 0.7, 0.8}       (memory weight; alpha+beta ≈ 1 for stability)\n"
        "    k ∈ {1.5, 2.0, 2.5, 3.0}     (multiplier of mean intensity for gate)\n"
        "REFERENCE IMPLEMENTATION:\n"
        "```python\n"
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); n = r.shape[0]\n"
        "    # Baseline fair estimator\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    # Hawkes self-excitation intensity (causal EWMA of return magnitude)\n"
        "    alpha = 0.3; beta = 0.7\n"
        "    absr = np.abs(np.where(np.isfinite(r), r, 0.0))\n"
        "    intensity = np.empty(n); intensity[0] = absr[0]\n"
        "    for i in range(1, n): intensity[i] = beta * intensity[i-1] + alpha * absr[i]\n"
        "    # Gate: abstain when intensity exceeds k * expanding_mean\n"
        "    ic = np.cumsum(intensity)\n"
        "    imean = ic / np.maximum(np.arange(1, n + 1), 1.0)\n"
        "    gate_ok = intensity <= 2.0 * imean\n"
        "    out = np.where(gate_ok, dev, np.nan)\n"
        "    return out\n"
        "```\n"
        "FAILURE PATTERNS:\n"
        "  - alpha=0.8, beta=0.2: intensity is just a noisy copy of |return|, gate flips randomly.\n"
        "  - alpha=0.1, beta=0.9: intensity is too sluggish, misses fast self-excitation episodes.\n"
        "  - k=1.0: blocks almost all bars after any moderate move, monthly counts collapse.\n"
        "  - k=5.0: gate never fires, behaves like baseline.\n"
        "  - alpha+beta > 1.0: intensity explodes, gate becomes permanently closed.\n"
        "CROSS-BRIDGE: Can combine with empirical_direction — use intensity to filter bars,\n"
        "  then let the conditional-response learner pick fade vs continue on the remainder.\n"
    ),
    "asymmetric_vol": (
        "BRANCH: asymmetric_vol — gate fades when downside Parkinson vol dominates upside\n"
        "FORMULA (Barndorff-Nielsen et al. 2010; Feunou & Okou 2019, JFQA):\n"
        "    1. down_parkinson = sqrt( sum_{vel<0}(range^2) / (4*ln2*W) )\n"
        "    2. up_parkinson   = sqrt( sum_{vel>=0}(range^2) / (4*ln2*W) )\n"
        "    3. ratio = down_parkinson / up_parkinson\n"
        "    4. Gate: fade only when ratio <= threshold\n"
        "RATIONALE:\n"
        "  Upside and downside volatility have different dynamics.  'Bad volatility' (downside)\n"
        "  predicts lower returns and carries a risk premium; 'good volatility' (upside) does not.\n"
        "  When downside Parkinson vol dominates, the market is in a panic-selling regime where\n"
        "  the efficient price itself may be discontinuously shifting downward.  Fading long\n"
        "  here is dangerous because the market may keep falling.  When upside vol dominates,\n"
        "  rallies are more likely to be noisy and mean-reverting.  This gate uses only the\n"
        "  existing features (returns and ranges) but decomposes them by direction, giving a\n"
        "  richer signal than total Parkinson vol alone.\n"
        "BAYESIAN ALIGNMENT:\n"
        "  The gate is one-sided (protects long fades).  Typically blocks ~15-25% of bars.\n"
        "  For symbols with persistent directional bias (e.g. JPY safe-haven flows), the ratio\n"
        "  may be chronically elevated; threshold must be high enough (>= 1.5) to avoid\n"
        "  collapsing monthly counts below _MIN_MONTHS=2.\n"
        "ALLOWED VARIATIONS:\n"
        "    W ∈ {10, 20, 40}              (Parkinson window)\n"
        "    threshold ∈ {1.2, 1.5, 2.0}   (down/up ratio above which we block)\n"
        "REFERENCE IMPLEMENTATION:\n"
        "```python\n"
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); br = ctx.col('bar_range_pips')\n"
        "    n = r.shape[0]; W = 20\n"
        "    # Baseline fair estimator\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    # Directional Parkinson volatility (down vs up)\n"
        "    down_sq = np.where(r < 0, br * br, 0.0)\n"
        "    up_sq   = np.where(r >= 0, br * br, 0.0)\n"
        "    c_down = np.concatenate(([0.0], np.cumsum(down_sq)))\n"
        "    c_up   = np.concatenate(([0.0], np.cumsum(up_sq)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "    ms = np.where(m > 0, m, 1.0)\n"
        "    pv_down = np.sqrt(np.clip((c_down[k]-c_down[lo])/(ms*4.0*np.log(2.0)), 1e-12, None))\n"
        "    pv_up   = np.sqrt(np.clip((c_up[k]-c_up[lo])/(ms*4.0*np.log(2.0)), 1e-12, None))\n"
        "    ratio = pv_down / (pv_up + 1e-9)\n"
        "    gate_ok = ratio <= 1.5\n"
        "    out = np.where((m >= 10) & gate_ok, dev, np.nan)\n"
        "    return out\n"
        "```\n"
        "FAILURE PATTERNS:\n"
        "  - threshold=0.8: blocks almost all bars in normal markets, counts collapse.\n"
        "  - threshold=3.0: too lenient, allows panic-selling fades, no protection.\n"
        "  - W=5: directional Parkinson is noisy, ratio oscillates, gate flips randomly.\n"
        "  - W=100: window too long, misses fast regime switches between up/down vol.\n"
        "CROSS-BRIDGE: Can combine with jump_aware — both detect market stress but via\n"
        "  different signals (range outliers vs directional vol decomposition).\n"
    ),
    "seasonality": (
        "BRANCH: seasonality — gate fades during FX fix windows (Krohn et al. 2024, J. Finance)\n"
        "FORMULA:\n"
        "    1. hour_utc = ctx.col('hour_utc')  (per-bar UTC hour as float)\n"
        "    2. fix_window = (hour_utc in [15.5, 16.5])   (London 16:00 UTC ±30 min)\n"
        "                 OR (hour_utc in [12.0, 13.5])   (ECB 14:15 CET ≈ 13:15 UTC winter / 12:15 summer)\n"
        "    3. Gate: fade only when NOT in fix_window\n"
        "RATIONALE (Krohn, Mueller & Whelan 2024, Journal of Finance):\n"
        "  FX follows a predictable W-shaped intraday pattern tied to three major fixes.\n"
        "  Dealers accumulate inventory ahead of each fix (pre-fix appreciation), then\n"
        "  execute fix orders at the fix itself, followed by post-fix reversal.  During\n"
        "  fix windows, microstructure is dominated by fix-order flow rather than noise.\n"
        "  The EWMA fair price lags the fix-driven dislocation, making fades dangerous.\n"
        "  Post-fix, the reversal is fast and the fair price is stale.  Blocking trades\n"
        "  during fix windows removes these systematically loss-making entries.\n"
        "BAYESIAN ALIGNMENT:\n"
        "  Each fix window blocks ~1-2 hours of bars per day (~4-8% of daily bars).\n"
        "  With three major trading sessions, monthly counts remain viable.  The gate is\n"
        "  calendar-based (deterministic), not stochastic, so it does not introduce\n"
        "  sampling variance into the Bayesian posterior.\n"
        "ALLOWED VARIATIONS:\n"
        "    london_start ∈ {15.0, 15.5, 16.0}   (London fix window start, UTC)\n"
        "    london_end   ∈ {16.0, 16.5, 17.0}   (London fix window end, UTC)\n"
        "    ecb_start    ∈ {12.0, 12.5, 13.0}   (ECB fix window start, UTC)\n"
        "    ecb_end      ∈ {13.0, 13.5, 14.0}   (ECB fix window end, UTC)\n"
        "    tokyo_fix    ∈ {True, False}        (include Tokyo 00:55 UTC window)\n"
        "REFERENCE IMPLEMENTATION:\n"
        "```python\n"
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); hr = ctx.col('hour_utc')\n"
        "    n = r.shape[0]\n"
        "    # Baseline fair estimator\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    # Fix windows: London 16:00 UTC and ECB ~13:00 UTC\n"
        "    in_fix = ((hr >= 15.5) & (hr <= 16.5)) | ((hr >= 12.0) & (hr <= 13.5))\n"
        "    gate_ok = ~in_fix\n"
        "    out = np.where(gate_ok, dev, np.nan)\n"
        "    return out\n"
        "```\n"
        "FAILURE PATTERNS:\n"
        "  - Window too wide (e.g. 14:00-18:00): blocks ~17% of bars, may drop monthly counts.\n"
        "  - Window too narrow (e.g. exactly 16:00 only): misses pre-fix build-up and post-fix reversal.\n"
        "  - Forgetting ECB window: London fix is only one of three; ECB is equally important for EUR.\n"
        "  - Tokyo window (00:00-01:00): may be irrelevant for European hours; test per symbol.\n"
        "CROSS-BRIDGE: Can combine with ANY gate — use fix-window as a temporal first-pass\n"
        "  filter, then apply VR, OFI, or liquidity on the remaining bars.\n"
    ),
    "microprice": (
        "BRANCH: microprice — imbalance-weighted fair value (Stoikov 2018 proxy)\n"
        "FORMULA: micro_fair = EWMA(cumsum(returns)) + k * imbalance * bar_range;\n"
        "         dev = micro_fair - cumsum(returns); side = sign(dev) (fade).\n"
        "RATIONALE: Stoikov (2018, 'The micro-price'). The mid is a biased estimate of"
        " the short-horizon price; the microprice tilts toward the heavier side. We lack"
        " L1 sizes at 100-tick bars, so we proxy imbalance by where the bar closed within"
        " its high-low range (hl_pos_delta_tick): a close near the high = buy pressure.\n"
        "PROXY LIMITATION: hl_pos_delta_tick is a coarse imbalance proxy; true microprice"
        " needs quote sizes.\n"
        "ALLOWED VARIATIONS: k in {0.25, 0.5, 1.0}; alpha in {0.03, 0.05, 0.10}\n"
        "FAILURE PATTERN: k too large (>1.5) makes the adjustment dominate the EWMA fair"
        " value, turning the signal into a pure close-position momentum proxy.\n"
    ),
    "flow_toxicity": (
        "BRANCH: flow_toxicity — VPIN order-flow toxicity gate\n"
        "FORMULA: VPIN ~= EWMA(|sign*volume|) / EWMA(volume); gate opens when VPIN <= thr.\n"
        "RATIONALE: Easley, Lopez de Prado & O'Hara (2012, RFS, 'Flow Toxicity and"
        " Liquidity'). High VPIN = one-sided/informed flow; fading into informed flow is"
        " adverse selection and loses. We proxy bucketed VPIN with a causal EWMA of"
        " |signed flow| over total flow from bar_return_sign * tick_volume, and fade only"
        " when toxicity is low (balanced two-sided flow).\n"
        "WHY thr=0.6: above ~0.6 marks sustained one-sided pressure with no fade edge.\n"
        "ALLOWED VARIATIONS: thr in {0.5, 0.6, 0.7}; b (EWMA) in {0.02, 0.05, 0.10}\n"
        "FAILURE PATTERN: thr too low (<0.4) gates out almost every bar (no trades); thr"
        " too high (>0.85) is effectively no gate and reverts to the baseline fade.\n"
    ),
}

# ── Cross-branch recombination prompts ───────────────────────────────────────
# These are used when PUCT selects two nodes from DIFFERENT branches for recombination.
# The LLM is told explicitly which ideas to combine and why they might synergise.
CROSS_BRANCH_PROMPTS: dict[tuple[str, str], str] = {
    ("mean_reversion_gate", "empirical_direction"): (
        "COMBINATION: mean_reversion_gate + empirical_direction\n"
        "SYNERGY: The variance-ratio gate tells us WHEN to trade (only in mean-reverting"
        " regimes), but it does not tell us WHICH DIRECTION.  The empirical-direction learner"
        " tells us WHICH DIRECTION by looking at past completed episodes.  Together they form"
        " a regime-aware, empirically-calibrated directional system: trade only when VR says"
        " revert, but let the online learner pick fade vs continue based on actual outcomes.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("regime_switching", "empirical_direction"): (
        "COMBINATION: regime_switching + empirical_direction\n"
        "SYNERGY: Regime-switching gives a fast, model-based direction (fade/continue from VR),"
        " but it can be wrong at regime boundaries.  The empirical learner gives a slower but"
        " more robust direction estimate from actual outcomes.  Combine them by using the"
        " empirical direction when enough episodes exist (nep >= MINEP), falling back to the"
        " regime-switching rule when the learner is still cold.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("mean_reversion_gate", "regime_switching"): (
        "COMBINATION: mean_reversion_gate + regime_switching\n"
        "SYNERGY: The mean_reversion_gate is a simple fade-only filter.  Regime_switching adds"
        " continuation when trending.  Combine them by using the mean-reversion gate as a"
        " pre-filter (only look at bars where some gate says regime is clear), then apply"
        " the regime-switching direction rule to those pre-selected bars.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("adaptive_estimation", "mean_reversion_gate"): (
        "COMBINATION: adaptive_estimation + mean_reversion_gate\n"
        "SYNERGY: The adaptive fair estimator produces a more responsive fair price during"
        " volatility spikes, but it does not tell us whether to trade.  The variance-ratio"
        " gate filters for mean-reverting regimes.  Together: an adaptive fair that catches"
        " dislocations faster, gated by VR so we only trade when reversion is likely.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("microstructure_gate", "empirical_direction"): (
        "COMBINATION: microstructure_gate + empirical_direction\n"
        "SYNERGY: The OFI proxy (range-return correlation) tells us WHEN the market is noisy"
        " (good fade), but not WHICH DIRECTION.  The empirical direction learner tells us"
        " WHICH DIRECTION from past completed episodes.  Combine: only enter when OFI says"
        " noise, but let the conditional-response learner pick fade vs continue.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("liquidity_gate", "mean_reversion_gate"): (
        "COMBINATION: liquidity_gate + mean_reversion_gate\n"
        "SYNERGY: The liquidity gate blocks trades during wide-spread or high-vol episodes"
        " where the fair-price model degrades.  The mean-reversion gate (variance ratio)"
        " identifies which remaining bars are actually reverting.  Together: only trade when"
        " liquidity is normal AND microstructure says revert.  This is a double-filter that"
        " should improve per-trade quality while keeping monthly counts viable.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("liquidity_gate", "adaptive_estimation"): (
        "COMBINATION: liquidity_gate + adaptive_estimation\n"
        "SYNERGY: The adaptive fair estimator already adjusts alpha to local volatility, but"
        " it does not block trades during extreme illiquidity.  The liquidity gate adds that"
        " block.  Together: a fair price that adapts to vol changes, but with trades halted"
        " when spread or Parkinson vol spikes beyond normal — the periods where even an"
        " adaptive fair is unreliable.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("liquidity_gate", "microstructure_gate"): (
        "COMBINATION: liquidity_gate + microstructure_gate\n"
        "SYNERGY: Both gates are microstructure-informed but orthogonal.  Liquidity gate"
        " reacts to spread and volatility conditions; the OFI gate reacts to the relationship"
        " between range and return (informed vs noise flow).  A bar can have normal spread"
        " but still be informed-flow driven (large range, directional move).  Combining both"
        " gives a more selective entry: trade only when liquidity is good AND the bar looks"
        " like noise rather than informed flow.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("transient_impact", "adaptive_estimation"): (
        "COMBINATION: transient_impact + adaptive_estimation\n"
        "SYNERGY: The adaptive fair estimator adjusts alpha to local volatility, producing a"
        " more responsive fair price.  The transient-impact adjustment subtracts estimated"
        " decaying trade impact from that fair price.  Together: a fair price that adapts to"
        " BOTH volatility changes (via Parkinson EWMA) AND flow-induced distortions (via"
        " propagator decay).  This is a double-cleansed fair that should be more reliable than"
        " either alone.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("transient_impact", "liquidity_gate"): (
        "COMBINATION: transient_impact + liquidity_gate\n"
        "SYNERGY: The transient-impact adjustment removes mechanical price pressure from the"
        " fair price, but it does not know when liquidity is degraded.  The liquidity gate"
        " blocks when spread or Parkinson vol spike.  Together: a cleansed fair price that is"
        " only traded when liquidity quality is normal.  This should avoid fading into"
        " impact-distorted prices during transient illiquidity.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("transient_impact", "mean_reversion_gate"): (
        "COMBINATION: transient_impact + mean_reversion_gate\n"
        "SYNERGY: The variance-ratio gate identifies mean-reverting regimes, but it operates"
        " on the raw mid which may be distorted by transient impact.  By first cleansing the"
        " fair price (subtracting decaying impact), the VR gate sees a more accurate mid and"
        " should make better regime classifications.  The result: cleaner regime detection +"
        " cleaner fair price = higher per-trade edge.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("jump_aware", "mean_reversion_gate"): (
        "COMBINATION: jump_aware + mean_reversion_gate\n"
        "SYNERGY: The variance-ratio gate is computed over a trailing window that includes"
        " jump bars.  Jumps inflate variance and corrupt the VR estimate, causing false regime"
        " classifications.  By pre-filtering jump bars (and their aftermath), the VR gate"
        " sees a cleaner sample and should produce more reliable mean-reversion signals.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("jump_aware", "empirical_direction"): (
        "COMBINATION: jump_aware + empirical_direction\n"
        "SYNERGY: The conditional-response learner uses past extreme dislocations to predict"
        " direction.  If a jump contaminates the training set, the learner memorizes jump"
        " aftermath as a signal, which is noise.  By filtering jumps before the learner sees"
        " episodes, the direction estimate trains on cleaner data and should generalise better.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("jump_aware", "liquidity_gate"): (
        "COMBINATION: jump_aware + liquidity_gate\n"
        "SYNERGY: Both are temporal / event-driven filters but detect different phenomena."
        " The liquidity gate blocks during elevated spread/vol (sustained illiquidity)."
        " The jump gate blocks during discontinuous range outliers (episodic microstructure"
        " events).  Together they cover both sustained and episodic degradation, giving a"
        " more robust trading schedule.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("flow_intensity", "mean_reversion_gate"): (
        "COMBINATION: flow_intensity + mean_reversion_gate\n"
        "SYNERGY: The variance-ratio gate identifies mean-reverting regimes, but it can be"
        " corrupted by self-exciting flow episodes where variance is inflated by persistent"
        " directional moves rather than genuine mean-reversion.  The Hawkes intensity filter"
        " removes these self-exciting episodes before the VR gate sees them.  Together:"
        " cleaner regime detection that is not fooled by cascades of directional bars.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("flow_intensity", "empirical_direction"): (
        "COMBINATION: flow_intensity + empirical_direction\n"
        "SYNERGY: The conditional-response learner needs clean training data.  Self-exciting"
        " flow episodes (Hawkes intensity spikes) create misleading episodes where direction"
        " appears to persist, biasing the learner toward continuation.  By filtering intensity"
        " spikes before training, the learner sees a more representative sample of normal-market"
        " dislocations and should generalise better.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("asymmetric_vol", "mean_reversion_gate"): (
        "COMBINATION: asymmetric_vol + mean_reversion_gate\n"
        "SYNERGY: The variance-ratio gate uses total variance, which is inflated during panic-"
        " selling episodes (high downside vol).  This causes false 'mean-reverting' signals"
        " when the market is actually crashing.  The asymmetric-vol gate removes these episodes"
        " by blocking when downside Parkinson dominates.  The VR gate then operates on a cleaner"
        " sample where variance truly reflects chop vs trend rather than one-sided panic.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("asymmetric_vol", "jump_aware"): (
        "COMBINATION: asymmetric_vol + jump_aware\n"
        "SYNERGY: Both detect market stress but via orthogonal signals.  Jump detection"
        " identifies episodic discontinuous moves (range outliers).  Asymmetric vol identifies"
        " sustained periods where downside volatility dominates (panic regimes).  Together they"
        " cover both sudden crashes and grinding sell-offs, providing comprehensive protection"
        " for fade strategies.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("asymmetric_vol", "liquidity_gate"): (
        "COMBINATION: asymmetric_vol + liquidity_gate\n"
        "SYNERGY: The liquidity gate blocks based on spread and total volatility levels."
        " The asymmetric-vol gate blocks based on the DIRECTION of volatility (down vs up)."
        " A market can have normal spread but still be in a bad-volatility regime (panic selling"
        " with tight spreads but persistent down moves).  Combining both gives a two-dimensional"
        " filter: trade only when liquidity is normal AND volatility is not one-sided.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("seasonality", "mean_reversion_gate"): (
        "COMBINATION: seasonality + mean_reversion_gate\n"
        "SYNERGY: The variance-ratio gate operates on a trailing window that includes fix-window"
        " bars.  Fix-driven moves inflate variance and create false regime classifications because"
        " the price action is mechanical (fix-order flow) rather than informative.  By pre-filtering"
        " fix windows, the VR gate sees a cleaner sample of normal-market microstructure and"
        " produces more reliable mean-reversion signals.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("seasonality", "empirical_direction"): (
        "COMBINATION: seasonality + empirical_direction\n"
        "SYNERGY: The conditional-response learner trains on past extreme dislocations.  Fix-"
        " window dislocations are driven by calendar effects (fix-order flow) rather than"
        " microstructure noise, so they generalise poorly.  By filtering fix windows before"
        " training, the learner sees only genuine microstructure episodes and should produce"
        " a more robust direction estimate.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("seasonality", "liquidity_gate"): (
        "COMBINATION: seasonality + liquidity_gate\n"
        "SYNERGY: Both are calendar-time filters but detect different liquidity phenomena."
        " The seasonality gate blocks deterministic fix windows where dealer inventory dynamics"
        " distort price discovery.  The liquidity gate blocks stochastic episodes of elevated"
        " spread or volatility.  Together they cover both scheduled and unscheduled liquidity"
        " degradation, giving a more complete trading schedule.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
    ("seasonality", "jump_aware"): (
        "COMBINATION: seasonality + jump_aware\n"
        "SYNERGY: Both are temporal abstention mechanisms but triggered by different signals."
        " Seasonality blocks deterministic calendar events (fixes).  Jump awareness blocks"
        " stochastic range outliers.  A bar can be outside a fix window but still contain a jump;"
        " conversely, fix windows often contain jumps.  Together they provide comprehensive"
        " temporal protection against both predictable and surprise microstructure events.\n"
        "Write a single `signal(ctx)` that combines both ideas.\n"
    ),
}

# Convenience: all ordered cross-branch pairs (A,B) and (B,A) map to the same prompt.
def _build_cross_branch_index():
    out = {}
    for (b1, b2), text in CROSS_BRANCH_PROMPTS.items():
        out[(b1, b2)] = text
        out[(b2, b1)] = text
    return out


CROSS_BRANCH_INDEX: dict[tuple[str, str], str] = _build_cross_branch_index()


# ── Seed programs (unchanged) ────────────────────────────────────────────────
FADE_SEED_PROGRAMS: dict[str, str] = {
    "fair_fade": (
        "def signal(ctx):\n" + _FAIR +
        "    return dev\n"
    ),
    "vr_gated_fade": (
        "def signal(ctx):\n" + _FAIR +
        "    W = 240; qv = 20\n"
        "    d1 = np.diff(p, prepend=p[0])\n"
        "    dq = np.empty(n); dq[:qv] = 0.0; dq[qv:] = p[qv:] - p[:-qv]\n"
        "    def rollvar(x):\n"
        "        c1 = np.concatenate(([0.0], np.cumsum(x)))\n"
        "        c2 = np.concatenate(([0.0], np.cumsum(x * x)))\n"
        "        k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "        ms = np.where(m > 0, m, 1.0)\n"
        "        mu = (c1[k] - c1[lo]) / ms\n"
        "        return (c2[k] - c2[lo]) / ms - mu * mu, m\n"
        "    v1, m = rollvar(d1); vq, _ = rollvar(dq)\n"
        "    vr = vq / (qv * v1 + 1e-12)\n"
        "    out = np.where((m >= 60) & (vr < 1.0), dev, np.nan)\n"
        "    return out\n"
    ),
    "vr_conditional_direction": (
        "def signal(ctx):\n" + _FAIR +
        "    W = 240; qv = 20\n"
        "    d1 = np.diff(p, prepend=p[0])\n"
        "    dq = np.empty(n); dq[:qv] = 0.0; dq[qv:] = p[qv:] - p[:-qv]\n"
        "    def rollvar(x):\n"
        "        c1 = np.concatenate(([0.0], np.cumsum(x)))\n"
        "        c2 = np.concatenate(([0.0], np.cumsum(x * x)))\n"
        "        k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "        ms = np.where(m > 0, m, 1.0)\n"
        "        mu = (c1[k] - c1[lo]) / ms\n"
        "        return (c2[k] - c2[lo]) / ms - mu * mu, m\n"
        "    v1, m = rollvar(d1); vq, _ = rollvar(dq)\n"
        "    vr = vq / (qv * v1 + 1e-12)\n"
        "    out = np.full(n, np.nan); ok = m >= 60\n"
        "    out = np.where(ok & (vr < 0.95), dev, out)   # mean-reverting -> FADE\n"
        "    out = np.where(ok & (vr > 1.05), -dev, out)  # trending -> CONTINUE\n"
        "    return out\n"
    ),
    "autocorr_gated_fade": (
        "def signal(ctx):\n" + _FAIR +
        "    W = 240; x = np.where(np.isfinite(r), r, 0.0); xp = np.concatenate(([0.0], x[:-1]))\n"
        "    cxx = np.concatenate(([0.0], np.cumsum(x * x)))\n"
        "    cxy = np.concatenate(([0.0], np.cumsum(x * xp)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "    rho = (cxy[k] - cxy[lo]) / (cxx[k] - cxx[lo] + 1e-12)\n"
        "    out = np.where((m >= 60) & (rho < 0.0), dev, np.nan)\n"
        "    return out\n"
    ),
    "efficiency_gated_fade": (
        "def signal(ctx):\n" + _FAIR +
        "    W = 120\n"
        "    absr = np.abs(np.where(np.isfinite(r), r, 0.0))\n"
        "    cabs = np.concatenate(([0.0], np.cumsum(absr)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "    net = np.abs(p - p[np.maximum(0, k - W)])\n"
        "    denom = cabs[k] - cabs[lo] + 1e-9\n"
        "    er = net / denom\n"
        "    out = np.where((m >= 60) & (er < 0.3), dev, np.nan)\n"
        "    return out\n"
    ),
    "extreme_fade": (
        "def signal(ctx):\n" + _FAIR +
        "    W = 240; ad = np.abs(np.where(np.isfinite(dev), dev, 0.0))\n"
        "    c = np.concatenate(([0.0], np.cumsum(ad)))\n"
        "    c2 = np.concatenate(([0.0], np.cumsum(ad * ad)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "    ms = np.where(m > 0, m, 1.0)\n"
        "    mu = (c[k] - c[lo]) / ms; var = (c2[k] - c2[lo]) / ms - mu * mu\n"
        "    sd = np.sqrt(np.clip(var, 1e-12, None))\n"
        "    out = np.where((m >= 60) & (ad > mu + 2.0 * sd), dev, np.nan)\n"
        "    return out\n"
    ),
    "conditional_response_fade": _cond_response_src(100),
    "conditional_response_fade_h200": _cond_response_src(200),
    "conditional_response_fade_h400": _cond_response_src(400),
    "conditional_response_signed": (
        "def signal(ctx):\n" + _FAIR +
        "    H = 100; W = 240; MINEP = 20\n"
        "    ad = np.abs(np.where(np.isfinite(dev), dev, 0.0))\n"
        "    c1 = np.concatenate(([0.0], np.cumsum(ad)))\n"
        "    c2 = np.concatenate(([0.0], np.cumsum(ad * ad)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); mwin = (k - lo).astype(float)\n"
        "    ms = np.where(mwin > 0, mwin, 1.0)\n"
        "    mu = (c1[k] - c1[lo]) / ms; var = (c2[k] - c2[lo]) / ms - mu * mu\n"
        "    sd = np.sqrt(np.clip(var, 1e-12, None))\n"
        "    ext = (mwin >= 60) & (ad > mu + 2.0 * sd)\n"
        "    pf = np.full(n, np.nan); pf[:n - H] = p[H:] - p[:n - H]\n"
        "    fr = np.sign(dev) * pf\n"
        "    def runmean(mask):\n"
        "        rs = np.full(n, np.nan); j = np.nonzero(mask & np.isfinite(fr))[0]\n"
        "        rs[j + H] = fr[j]; fn = np.isfinite(rs)\n"
        "        ct = np.cumsum(np.where(fn, 1.0, 0.0))\n"
        "        return np.cumsum(np.where(fn, rs, 0.0)) / np.maximum(ct, 1.0), ct\n"
        "    Rp, ep = runmean(ext & (dev > 0)); Rn, en = runmean(ext & (dev <= 0))\n"
        "    use_p = dev > 0\n"
        "    R = np.where(use_p, Rp, Rn); nep = np.where(use_p, ep, en)\n"
        "    direction = np.where(R >= 0.0, 1.0, -1.0)\n"
        "    out = np.where(nep >= MINEP, dev * direction, np.nan)\n"
        "    return out\n"
    ),
    "adaptive_fair": (
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); br = ctx.col('bar_range_pips')\n"
        "    n = r.shape[0]\n"
        "    W = 20\n"
        "    # Parkinson volatility (causal trailing): sqrt( sum(range^2) / (4*ln2*W) )\n"
        "    c = np.concatenate(([0.0], np.cumsum(br * br)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "    ms = np.where(m > 0, m, 1.0)\n"
        "    parkinson = np.sqrt(np.clip((c[k] - c[lo]) / (ms * 4.0 * np.log(2.0)), 1e-12, None))\n"
        "    # Adaptive alpha: higher vol -> faster adaptation (higher alpha)\n"
        "    # Causal expanding mean as reference (not global median)\n"
        "    vol_cum = np.cumsum(np.where(np.isfinite(parkinson), parkinson, 0.0))\n"
        "    vol_cnt = np.cumsum(np.where(np.isfinite(parkinson), 1.0, 0.0))\n"
        "    vol_ref = vol_cum / np.maximum(vol_cnt, 1.0)\n"
        "    alpha = np.clip(0.02 + 0.08 * (parkinson / (vol_ref + 1e-9)), 0.02, 0.10)\n"
        "    # Causal EWMA fair price with per-bar alpha\n"
        "    p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n):\n"
        "        acc = (1 - alpha[i]) * acc + alpha[i] * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    return dev\n"
    ),
    "ofi_gated_fade": (
        "def signal(ctx):\n" + _FAIR +
        "    br = ctx.col('bar_range_pips')\n"
        "    W = 20\n"
        "    # Range/Return Correlation (Cont-Kukanov OFI proxy)\n"
        "    # Large range + small return => noise => good fade\n"
        "    # Large range + large return => informed flow => abstain\n"
        "    absr = np.abs(np.where(np.isfinite(r), r, 0.0))\n"
        "    s_x = np.concatenate(([0.0], np.cumsum(absr)))\n"
        "    s_y = np.concatenate(([0.0], np.cumsum(br)))\n"
        "    s_xy = np.concatenate(([0.0], np.cumsum(absr * br)))\n"
        "    s_x2 = np.concatenate(([0.0], np.cumsum(absr * absr)))\n"
        "    s_y2 = np.concatenate(([0.0], np.cumsum(br * br)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "    ms = np.where(m > 0, m, 1.0)\n"
        "    mx = (s_x[k] - s_x[lo]) / ms\n"
        "    my = (s_y[k] - s_y[lo]) / ms\n"
        "    mxy = (s_xy[k] - s_xy[lo]) / ms\n"
        "    mx2 = (s_x2[k] - s_x2[lo]) / ms\n"
        "    my2 = (s_y2[k] - s_y2[lo]) / ms\n"
        "    cov = mxy - mx * my\n"
        "    var_x = np.clip(mx2 - mx * mx, 1e-12, None)\n"
        "    var_y = np.clip(my2 - my * my, 1e-12, None)\n"
        "    rrc = cov / np.sqrt(var_x * var_y)\n"
        "    # Gate: fade only when |rrc| is low (range and return uncorrelated => noise)\n"
        "    out = np.where((m >= 10) & (np.abs(rrc) < 0.3), dev, np.nan)\n"
        "    return out\n"
    ),
    "spread_vol_gate": (
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); br = ctx.col('bar_range_pips'); sz = ctx.col('spread_z')\n"
        "    n = r.shape[0]\n"
        "    W = 20\n"
        "    # Parkinson volatility (causal trailing window)\n"
        "    c = np.concatenate(([0.0], np.cumsum(br * br)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "    ms = np.where(m > 0, m, 1.0)\n"
        "    parkinson = np.sqrt(np.clip((c[k] - c[lo]) / (ms * 4.0 * np.log(2.0)), 1e-12, None))\n"
        "    # Causal expanding mean of Parkinson vol\n"
        "    pv_cum = np.cumsum(np.where(np.isfinite(parkinson), parkinson, 0.0))\n"
        "    pv_cnt = np.cumsum(np.where(np.isfinite(parkinson), 1.0, 0.0))\n"
        "    pv_ref = pv_cum / np.maximum(pv_cnt, 1.0)\n"
        "    # Gate: normal spread AND normal volatility\n"
        "    gate_ok = (np.abs(sz) <= 2.0) & (parkinson <= 1.5 * pv_ref)\n"
        "    # Baseline fair estimator\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    out = np.where((m >= 10) & gate_ok, dev, np.nan)\n"
        "    return out\n"
    ),
    "transient_impact_fade": (
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); br = ctx.col('bar_range_pips')\n"
        "    n = r.shape[0]\n"
        "    # Baseline fair estimator\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    # Transient impact: decaying sum of past bar ranges (Barzykin 2025/2026)\n"
        "    rho = 0.1; lam = 0.5\n"
        "    impact = np.zeros(n)\n"
        "    for i in range(1, n): impact[i] = (1 - rho) * impact[i-1] + lam * br[i-1]\n"
        "    dev_adj = dev - impact\n"
        "    # Gate: only trade when impact is not extreme (causal expanding mean)\n"
        "    iabs = np.abs(impact); ic = np.cumsum(iabs)\n"
        "    imean = ic / np.maximum(np.arange(1, n + 1), 1.0)\n"
        "    gate_ok = iabs <= 2.0 * imean\n"
        "    out = np.where(gate_ok, dev_adj, np.nan)\n"
        "    return out\n"
    ),
    "jump_aware_fade": (
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); br = ctx.col('bar_range_pips')\n"
        "    n = r.shape[0]; W = 20\n"
        "    # Parkinson volatility (causal trailing)\n"
        "    c = np.concatenate(([0.0], np.cumsum(br * br)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "    ms = np.where(m > 0, m, 1.0)\n"
        "    parkinson = np.sqrt(np.clip((c[k]-c[lo])/(ms*4.0*np.log(2.0)), 1e-12, None))\n"
        "    # Jump detection: bar range > k * Parkinson vol\n"
        "    jump = br > 4.0 * parkinson\n"
        "    # Causal cooling-off: abstain for cooldown bars after any jump\n"
        "    cooldown = 5\n"
        "    cj = np.concatenate(([0.0], np.cumsum(jump.astype(float))))\n"
        "    lo_cd = np.maximum(0, k - cooldown + 1)\n"
        "    recent_jump = (cj[k + 1] - cj[lo_cd]) > 0\n"
        "    gate_ok = ~recent_jump\n"
        "    # Baseline fair estimator\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    out = np.where((m >= 10) & gate_ok, dev, np.nan)\n"
        "    return out\n"
    ),
    "hawkes_gate": (
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); n = r.shape[0]\n"
        "    # Baseline fair estimator\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    # Hawkes self-excitation intensity (causal EWMA of return magnitude)\n"
        "    alpha = 0.3; beta = 0.7\n"
        "    absr = np.abs(np.where(np.isfinite(r), r, 0.0))\n"
        "    intensity = np.empty(n); intensity[0] = absr[0]\n"
        "    for i in range(1, n): intensity[i] = beta * intensity[i-1] + alpha * absr[i]\n"
        "    # Gate: abstain when intensity exceeds k * expanding_mean\n"
        "    ic = np.cumsum(intensity)\n"
        "    imean = ic / np.maximum(np.arange(1, n + 1), 1.0)\n"
        "    gate_ok = intensity <= 2.0 * imean\n"
        "    out = np.where(gate_ok, dev, np.nan)\n"
        "    return out\n"
    ),
    "asymmetric_vol_gate": (
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); br = ctx.col('bar_range_pips')\n"
        "    n = r.shape[0]; W = 20\n"
        "    # Baseline fair estimator\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    # Directional Parkinson volatility (down vs up)\n"
        "    down_sq = np.where(r < 0, br * br, 0.0)\n"
        "    up_sq   = np.where(r >= 0, br * br, 0.0)\n"
        "    c_down = np.concatenate(([0.0], np.cumsum(down_sq)))\n"
        "    c_up   = np.concatenate(([0.0], np.cumsum(up_sq)))\n"
        "    k = np.arange(n); lo = np.maximum(0, k - W); m = (k - lo).astype(float)\n"
        "    ms = np.where(m > 0, m, 1.0)\n"
        "    pv_down = np.sqrt(np.clip((c_down[k]-c_down[lo])/(ms*4.0*np.log(2.0)), 1e-12, None))\n"
        "    pv_up   = np.sqrt(np.clip((c_up[k]-c_up[lo])/(ms*4.0*np.log(2.0)), 1e-12, None))\n"
        "    ratio = pv_down / (pv_up + 1e-9)\n"
        "    gate_ok = ratio <= 1.5\n"
        "    out = np.where((m >= 10) & gate_ok, dev, np.nan)\n"
        "    return out\n"
    ),
    "fix_window_gate": (
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); hr = ctx.col('hour_utc')\n"
        "    n = r.shape[0]\n"
        "    # Baseline fair estimator\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    # Fix windows: London 16:00 UTC and ECB ~13:00 UTC (Krohn et al. 2024, JF)\n"
        "    in_fix = ((hr >= 15.5) & (hr <= 16.5)) | ((hr >= 12.0) & (hr <= 13.5))\n"
        "    gate_ok = ~in_fix\n"
        "    out = np.where(gate_ok, dev, np.nan)\n"
        "    return out\n"
    ),
    "microprice_fade": (
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); imb = ctx.col('hl_pos_delta_tick')\n"
        "    rng_ = ctx.col('bar_range_pips'); n = r.shape[0]\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    k = 0.5\n"
        "    adj = np.where(np.isfinite(imb) & np.isfinite(rng_), k * imb * rng_, 0.0)\n"
        "    micro_fair = ew + adj\n"
        "    dev = micro_fair - p\n"
        "    return dev\n"
    ),
    "vpin_gated_fade": (
        "def signal(ctx):\n"
        "    r = ctx.col('vel_pips_h1'); sgn = ctx.col('bar_return_sign')\n"
        "    vol = ctx.col('tick_volume'); n = r.shape[0]\n"
        "    a = 0.05; p = np.cumsum(np.where(np.isfinite(r), r, 0.0))\n"
        "    ew = np.empty(n); acc = p[0]\n"
        "    for i in range(n): acc = (1 - a) * acc + a * p[i]; ew[i] = acc\n"
        "    dev = ew - p\n"
        "    v = np.where(np.isfinite(vol), vol, 0.0)\n"
        "    sg = np.where(np.isfinite(sgn), sgn, 0.0)\n"
        "    signed = np.abs(sg * v)\n"
        "    b = 0.05\n"
        "    es = np.empty(n); et = np.empty(n); accs = signed[0]; acct = v[0] + 1e-9\n"
        "    for i in range(n):\n"
        "        accs = (1 - b) * accs + b * signed[i]; es[i] = accs\n"
        "        acct = (1 - b) * acct + b * v[i]; et[i] = acct\n"
        "    vpin = es / (et + 1e-9)\n"
        "    gate_ok = vpin <= 1.0\n"
        "    out = np.where(gate_ok, dev, np.nan)\n"
        "    return out\n"
    ),
}

BASELINE_SEED_NAMES = ("fair_fade", "vr_gated_fade", "autocorr_gated_fade", "extreme_fade")

# Legacy one-liner ideas — kept for backward compatibility with callers that expect
# a plain list of strings.  New branch-aware code should prefer RICH_TEMPLATES.
RESEARCH_IDEAS: list[str] = [
    "Variance ratio regime (Lo-MacKinlay 1988): the fade only pays when price mean-reverts; gate on "
    "a causal trailing variance ratio < 1 (q-step variance below q x 1-step variance).",
    "Lag-1 autocorrelation: negative trailing return autocorrelation = reverting; trade then.",
    "Kaufman efficiency ratio: |net move| / sum|moves| over a window; low ER = choppy/reverting "
    "(not trending) = good for fading.",
    "OU half-life (Leung-Li; Bertram): estimate a short reversion half-life on a trailing window; "
    "fade when reversion is fast and size the exit horizon to it.",
    "Extreme dislocation: only fade when |fair - mid| is in the tail of its own trailing "
    "distribution (e.g. > mean + 2 sd) - the edge is tail-concentrated.",
    "Combine: gate the fair-mispricing fade by a mean-reversion regime AND require an extreme "
    "dislocation; this opens a way in for otherwise-trending symbols (CHF/JPY) in their reverting "
    "windows without breaking the mean-reverting ones (EUR/AUD).",
    "Regime-conditional direction: do not assume reversion. Use the SAME causal trailing variance "
    "ratio to pick the side per bar - fade (toward fair) when VR<1 (mean-reverting), but go WITH the "
    "move (continuation) when VR>1 (trending), abstaining in a dead-band near 1. One causal rule, no "
    "per-symbol direction fitting; recovers EUR/AUD fade and GBP continuation from the regime alone.",
    "Entry-conditioned conditional response: do not gate direction by a trailing-average regime "
    "(which misclassifies the mean-reverting majors at the tail dislocations). Instead maintain a "
    "causal online mean of how the symbol's OWN past EXTREME dislocations resolved over the next H "
    "bars (completed episodes only), and fade when reversion has paid, continue when it has not. "
    "Empirical conditional-response/reversion function; learns direction per symbol with no peeking.",
    "Horizon-matched conditional response: learn the conditional reversion outcome over the SAME horizon "
    "the trade is held (internal H == exit h), not a fixed H. The fixed-H seed was strong only where its "
    "learning horizon coincided with the holding horizon; matching them tests whether the (q,h) collapse "
    "was a horizon mismatch rather than a horizon-specific edge.",
]
