default:
  AUD/CAD: 1.0
  AUD/NZD: 1.0
  CAC/NZD: 1.0
  CHF/JPY: 1.0
  EUR/AUD: 1.0
  EUR/CHF: 1.0
  EUR/GBP: 1.0
  EUR/JPY: 1.0
  GBP/AUD: 1.0
  GBP/CAD: 1.0
  GBP/JPY: 1.0
  Gold/Oil: 1.0
  Gold/Silver: 1.0
  NZD/CAD: 1.0
  Oil/Silver: 1.0
  SPX/CAC: 1.0
  SPX/DAX: 1.0
  SPX/Dow: 1.0
  SPX/FTSE: 1.0
  SPX/HK: 1.0
  SPX/Nas: 1.0
  SPX/Nikkei: 1.0
