#!/usr/bin/env python3
"""
Select top-2 promoted mixed strategies and materialize filtered report slices.

Inputs:
- meta mixed summary CSV from scripts/meta_triple_barrier_mixed_dd.py
- strategy overall/yearly/pair/pair_yearly CSVs from scripts/report_strategy_fx_comm_multi_tf.py

Outputs:
- recommended top-2 table
- mixed-only top-2 filtered overall/yearly/pair/pair_yearly tables
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


DEFAULT_ANALYSIS_DIR = Path("data/analysis")


def _load_required(path: Path, required: set[str]) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Missing file: {path}")
    df = pd.read_csv(path)
    missing = sorted(required.difference(df.columns))
    if missing:
        raise ValueError(f"{path} missing required columns: {missing}")
    return df


def _top_k_from_summary(summary: pd.DataFrame, top_k: int) -> pd.DataFrame:
    promoted = summary[summary["variant"].astype(str) == "meta_tb_promoted"].copy()
    baseline = summary[summary["variant"].astype(str) == "baseline_causal"].copy()
    if promoted.empty or baseline.empty:
        raise ValueError("Summary must include both baseline_causal and meta_tb_promoted variants.")

    bcols = [
        "mix_id",
        "trades",
        "mean_pnl_per_trade_bps",
        "sharpe",
        "annualized_bps_calendar",
        "max_daily_dd_bps",
        "max_dd_pct",
    ]
    base = baseline[bcols].rename(
        columns={
            "trades": "base_trades",
            "mean_pnl_per_trade_bps": "base_mean_pnl_per_trade_bps",
            "sharpe": "base_sharpe",
            "annualized_bps_calendar": "base_annualized_bps_calendar",
            "max_daily_dd_bps": "base_max_daily_dd_bps",
            "max_dd_pct": "base_max_dd_pct",
        }
    )

    merged = promoted.merge(base, on="mix_id", how="left")
    merged["delta_trades"] = merged["trades"] - merged["base_trades"]
    merged["delta_mean_pnl_per_trade_bps"] = (
        merged["mean_pnl_per_trade_bps"] - merged["base_mean_pnl_per_trade_bps"]
    )
    merged["delta_sharpe"] = merged["sharpe"] - merged["base_sharpe"]
    merged["delta_annualized_bps_calendar"] = (
        merged["annualized_bps_calendar"] - merged["base_annualized_bps_calendar"]
    )
    merged["delta_max_daily_dd_bps"] = merged["max_daily_dd_bps"] - merged["base_max_daily_dd_bps"]
    merged["delta_max_dd_pct"] = merged["max_dd_pct"] - merged["base_max_dd_pct"]

    ranked = merged.sort_values(["sharpe", "annualized_bps_calendar"], ascending=[False, False]).head(top_k).copy()
    ranked.insert(0, "rank", list(range(1, len(ranked) + 1)))
    return ranked


def _filter_mixed_top2(df: pd.DataFrame, mixes: list[str]) -> pd.DataFrame:
    if df.empty or "variant" not in df.columns:
        return df.copy()
    if "timeframe" in df.columns:
        df = df[df["timeframe"].astype(str) == "mixed"].copy()
    prefixes = [f"mixed_{m}__" for m in mixes]
    mask = pd.Series(False, index=df.index)
    variants = df["variant"].astype(str)
    for pref in prefixes:
        mask = mask | variants.str.startswith(pref)
    return df[mask].copy()


def main() -> None:
    parser = argparse.ArgumentParser(description="Select top-2 mixed strategies and write filtered report slices.")
    parser.add_argument(
        "--analysis-dir",
        default=str(DEFAULT_ANALYSIS_DIR),
        help="analysis directory containing summary and strategy report CSVs",
    )
    parser.add_argument(
        "--summary-file",
        default="meta_tb_mixed_no_oil_allmix_summary.csv",
        help="mixed summary CSV generated by meta_triple_barrier_mixed_dd.py",
    )
    parser.add_argument(
        "--overall-file",
        default="strategy_fx_comm_no_oil_overall.csv",
        help="overall report CSV generated by report_strategy_fx_comm_multi_tf.py",
    )
    parser.add_argument(
        "--yearly-file",
        default="strategy_fx_comm_no_oil_yearly.csv",
        help="yearly report CSV generated by report_strategy_fx_comm_multi_tf.py",
    )
    parser.add_argument(
        "--pair-file",
        default="strategy_fx_comm_no_oil_pair.csv",
        help="pair report CSV generated by report_strategy_fx_comm_multi_tf.py",
    )
    parser.add_argument(
        "--pair-yearly-file",
        default="strategy_fx_comm_no_oil_pair_yearly.csv",
        help="pair-yearly report CSV generated by report_strategy_fx_comm_multi_tf.py",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=2,
        help="number of mixes to select by promoted Sharpe/annualized_bps",
    )
    parser.add_argument(
        "--out-prefix",
        default="strategy_fx_comm_no_oil_mixed_top2",
        help="output prefix for filtered mixed tables",
    )
    parser.add_argument(
        "--recommended-file",
        default="meta_tb_mixed_no_oil_allmix_recommended_top2.csv",
        help="filename for the recommended top-k table",
    )
    args = parser.parse_args()

    analysis_dir = Path(args.analysis_dir)
    summary_path = analysis_dir / args.summary_file
    overall_path = analysis_dir / args.overall_file
    yearly_path = analysis_dir / args.yearly_file
    pair_path = analysis_dir / args.pair_file
    pair_yearly_path = analysis_dir / args.pair_yearly_file

    summary = _load_required(summary_path, {"mix_id", "variant", "trades", "mean_pnl_per_trade_bps", "sharpe", "annualized_bps_calendar", "max_daily_dd_bps", "max_dd_pct"})
    overall = _load_required(overall_path, {"variant"})
    yearly = _load_required(yearly_path, {"variant"})
    pair = _load_required(pair_path, {"variant"})
    pair_yearly = _load_required(pair_yearly_path, {"variant"})

    top = _top_k_from_summary(summary, top_k=max(1, int(args.top_k)))
    mixes = top["mix_id"].astype(str).tolist()

    out_recommended = analysis_dir / args.recommended_file
    out_overall = analysis_dir / f"{args.out_prefix}_overall.csv"
    out_yearly = analysis_dir / f"{args.out_prefix}_yearly.csv"
    out_pair = analysis_dir / f"{args.out_prefix}_pair.csv"
    out_pair_yearly = analysis_dir / f"{args.out_prefix}_pair_yearly.csv"

    _filter_mixed_top2(overall, mixes).to_csv(out_overall, index=False)
    _filter_mixed_top2(yearly, mixes).to_csv(out_yearly, index=False)
    _filter_mixed_top2(pair, mixes).to_csv(out_pair, index=False)
    _filter_mixed_top2(pair_yearly, mixes).to_csv(out_pair_yearly, index=False)
    top.to_csv(out_recommended, index=False)

    print("Top mixes:")
    for mix in mixes:
        print(f"- {mix}")
    print("\nSaved:")
    print(f"- {out_recommended}")
    print(f"- {out_overall}")
    print(f"- {out_yearly}")
    print(f"- {out_pair}")
    print(f"- {out_pair_yearly}")


if __name__ == "__main__":
    main()
