"""Shared diagnostic report rendering and artifact writing."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd


def markdown_table(df: pd.DataFrame) -> str:
    if df.empty:
        return "_empty_"
    try:
        return df.to_markdown(index=False)
    except Exception:
        return df.to_string(index=False)


def _json_default(value: object) -> object:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, pd.Timestamp):
        return value.isoformat()
    if isinstance(value, datetime):
        return pd.Timestamp(value).isoformat()
    return str(value)


def write_manifest(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(
        json.dumps(payload, indent=2, default=_json_default),
        encoding="utf-8",
    )


def _subreport_slot_status(path: object) -> str:
    if Path(str(path)).exists():
        return "available at render time"
    return "reference path; not generated by this run"


def render_reconcile_report(
    *,
    manifest: dict[str, object],
    findings: pd.DataFrame,
    results: pd.DataFrame,
) -> str:
    generated_at_utc = manifest.get("generated_at_utc", "")
    run_id = manifest.get("run_id", "")
    subreports = manifest.get("subreports")
    subreport_section: list[str] = []
    if isinstance(subreports, dict) and subreports:
        subreport_section = [
            "## Existing Diagnostic Subreport Slots",
            "",
            *[
                f"- {name}: `{path}` "
                f"({_subreport_slot_status(path)})"
                for name, path in sorted(subreports.items(), key=lambda item: item[0])
            ],
            "",
        ]

    sections = [
        "# JForex Outcome Reconciliation Report",
        "",
        f"- generated_at_utc: {generated_at_utc}",
        f"- run_id: {run_id}",
        "",
        (
            "This report is diagnostic evidence only and is not a Promotion gate; "
            "Promotion authority remains with the stage certification process."
        ),
        "",
        "## Findings",
        "",
        markdown_table(findings),
        "",
        *subreport_section,
        "## Reconciliation Summary",
        "",
        markdown_table(results),
        "",
    ]
    return "\n".join(sections)


def write_csv_bundle(run_dir: Path, frames: dict[str, pd.DataFrame]) -> None:
    run_dir.mkdir(parents=True, exist_ok=True)
    for name, df in frames.items():
        path = run_dir / f"{name}.csv"
        df.to_csv(path, index=False)
